// <auto-generated />
using System;
using GestioneVeicoli.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestioneVeicoli.Data.Migrations
{
    [DbContext(typeof(VeicoliDbContext))]
    [Migration("20250512141249_AddManutenzioniTable")]
    partial class AddManutenzioniTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Manutenzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoIntervento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Proprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Proprietari");
                });

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Veicolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("Targa")
                        .IsUnique();

                    b.ToTable("Veicoli");
                });

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Manutenzione", b =>
                {
                    b.HasOne("GestioneVeicoli.Data.Models.Veicolo", "Veicolo")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Veicolo", b =>
                {
                    b.HasOne("GestioneVeicoli.Data.Models.Proprietario", null)
                        .WithMany("Veicoli")
                        .HasForeignKey("ProprietarioId");
                });

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Proprietario", b =>
                {
                    b.Navigation("Veicoli");
                });

            modelBuilder.Entity("GestioneVeicoli.Data.Models.Veicolo", b =>
                {
                    b.Navigation("Manutenzioni");
                });
#pragma warning restore 612, 618
        }
    }
}
