// <auto-generated />
using System;
using CarDesk.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDesk.Data.Migrations
{
    [DbContext(typeof(CarDeskDbContext))]
    [Migration("20250715093258_AggiuntaUnicitaCodiceFiscale")]
    partial class AggiuntaUnicitaCodiceFiscale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDesk.Data.Models.Manutenzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Proprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LuogoNascita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique();

                    b.ToTable("Proprietari");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Veicolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alimentazione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("Targa")
                        .IsUnique();

                    b.ToTable("Veicoli");
                });

            modelBuilder.Entity("CarDesk.Data.Models.VoceIntervento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManutenzioneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManutenzioneId");

                    b.ToTable("VoceIntervento");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Manutenzione", b =>
                {
                    b.HasOne("CarDesk.Data.Models.Veicolo", "Veicolo")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Veicolo", b =>
                {
                    b.HasOne("CarDesk.Data.Models.Proprietario", "Proprietario")
                        .WithMany("Veicoli")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("CarDesk.Data.Models.VoceIntervento", b =>
                {
                    b.HasOne("CarDesk.Data.Models.Manutenzione", "Manutenzione")
                        .WithMany("VociIntervento")
                        .HasForeignKey("ManutenzioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manutenzione");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Manutenzione", b =>
                {
                    b.Navigation("VociIntervento");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Proprietario", b =>
                {
                    b.Navigation("Veicoli");
                });

            modelBuilder.Entity("CarDesk.Data.Models.Veicolo", b =>
                {
                    b.Navigation("Manutenzioni");
                });
#pragma warning restore 612, 618
        }
    }
}
